## The name of the environment matching the repository name
name: sidrees2023
## I prefer conda-forge packages for my projects
channels:
- conda-forge
- defaults
## Start with Python and include everything you need
dependencies:
- python=3.10
- numpy=1.23.1
- scipy=1.9.0
- scikit-image=0.19.3
- mpi4py=3.1.3
- matplotlib=3.5.2
- h5py
- pip